"""renamed address

Revision ID: 314473e0cce8
Revises: ba7b03713ccb
Create Date: 2024-10-07 12:40:42.147638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314473e0cce8'
down_revision = 'ba7b03713ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
